// Code generated by Kitex v0.16.2. DO NOT EDIT.

package operationsservice

import (
	"context"
	v1 "github.com/asherzj/financial_configuration_center/kitex_gen/finconfig/control/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListOutboxEvents(ctx context.Context, Req *v1.ListOutboxEventsRequest, callOptions ...callopt.Option) (r *v1.ListOutboxEventsResponse, err error)
	ReplayOutboxEvent(ctx context.Context, Req *v1.ReplayOutboxEventRequest, callOptions ...callopt.Option) (r *v1.ReplayOutboxEventResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOperationsServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOperationsServiceClient struct {
	*kClient
}

func (p *kOperationsServiceClient) ListOutboxEvents(ctx context.Context, Req *v1.ListOutboxEventsRequest, callOptions ...callopt.Option) (r *v1.ListOutboxEventsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOutboxEvents(ctx, Req)
}

func (p *kOperationsServiceClient) ReplayOutboxEvent(ctx context.Context, Req *v1.ReplayOutboxEventRequest, callOptions ...callopt.Option) (r *v1.ReplayOutboxEventResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReplayOutboxEvent(ctx, Req)
}
