// Code generated by Kitex v0.16.2. DO NOT EDIT.

package sensitiveaccessservice

import (
	"context"
	"errors"
	v1 "github.com/asherzj/financial_configuration_center/contracts/kitex_gen/finconfig/control/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"RevealField": kitex.NewMethodInfo(
		revealFieldHandler,
		newRevealFieldArgs,
		newRevealFieldResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	sensitiveAccessServiceServiceInfo                = NewServiceInfo()
	sensitiveAccessServiceServiceInfoForClient       = NewServiceInfoForClient()
	sensitiveAccessServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return sensitiveAccessServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return sensitiveAccessServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return sensitiveAccessServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SensitiveAccessService"
	handlerType := (*v1.SensitiveAccessService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finconfig.control.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func revealFieldHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.RevealFieldRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.SensitiveAccessService).RevealField(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RevealFieldArgs:
		success, err := handler.(v1.SensitiveAccessService).RevealField(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RevealFieldResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRevealFieldArgs() interface{} {
	return &RevealFieldArgs{}
}

func newRevealFieldResult() interface{} {
	return &RevealFieldResult{}
}

type RevealFieldArgs struct {
	Req *v1.RevealFieldRequest
}

func (p *RevealFieldArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RevealFieldArgs) Unmarshal(in []byte) error {
	msg := new(v1.RevealFieldRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RevealFieldArgs_Req_DEFAULT *v1.RevealFieldRequest

func (p *RevealFieldArgs) GetReq() *v1.RevealFieldRequest {
	if !p.IsSetReq() {
		return RevealFieldArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RevealFieldArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RevealFieldArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RevealFieldResult struct {
	Success *v1.RevealFieldResponse
}

var RevealFieldResult_Success_DEFAULT *v1.RevealFieldResponse

func (p *RevealFieldResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RevealFieldResult) Unmarshal(in []byte) error {
	msg := new(v1.RevealFieldResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RevealFieldResult) GetSuccess() *v1.RevealFieldResponse {
	if !p.IsSetSuccess() {
		return RevealFieldResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RevealFieldResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.RevealFieldResponse)
}

func (p *RevealFieldResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RevealFieldResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RevealField(ctx context.Context, Req *v1.RevealFieldRequest) (r *v1.RevealFieldResponse, err error) {
	var _args RevealFieldArgs
	_args.Req = Req
	var _result RevealFieldResult
	if err = p.c.Call(ctx, "RevealField", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
