// Code generated by Kitex v0.16.2. DO NOT EDIT.

package refreshservice

import (
	"context"
	"errors"
	v1 "github.com/asherzj/financial_configuration_center/contracts/kitex_gen/finconfig/config/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Notify": kitex.NewMethodInfo(
		notifyHandler,
		newNotifyArgs,
		newNotifyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	refreshServiceServiceInfo                = NewServiceInfo()
	refreshServiceServiceInfoForClient       = NewServiceInfoForClient()
	refreshServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return refreshServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return refreshServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return refreshServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RefreshService"
	handlerType := (*v1.RefreshService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finconfig.config.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func notifyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.NotifyRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.RefreshService).Notify(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *NotifyArgs:
		success, err := handler.(v1.RefreshService).Notify(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*NotifyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newNotifyArgs() interface{} {
	return &NotifyArgs{}
}

func newNotifyResult() interface{} {
	return &NotifyResult{}
}

type NotifyArgs struct {
	Req *v1.NotifyRequest
}

func (p *NotifyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *NotifyArgs) Unmarshal(in []byte) error {
	msg := new(v1.NotifyRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var NotifyArgs_Req_DEFAULT *v1.NotifyRequest

func (p *NotifyArgs) GetReq() *v1.NotifyRequest {
	if !p.IsSetReq() {
		return NotifyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *NotifyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *NotifyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type NotifyResult struct {
	Success *v1.NotifyResponse
}

var NotifyResult_Success_DEFAULT *v1.NotifyResponse

func (p *NotifyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *NotifyResult) Unmarshal(in []byte) error {
	msg := new(v1.NotifyResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *NotifyResult) GetSuccess() *v1.NotifyResponse {
	if !p.IsSetSuccess() {
		return NotifyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *NotifyResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.NotifyResponse)
}

func (p *NotifyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *NotifyResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Notify(ctx context.Context, Req *v1.NotifyRequest) (r *v1.NotifyResponse, err error) {
	var _args NotifyArgs
	_args.Req = Req
	var _result NotifyResult
	if err = p.c.Call(ctx, "Notify", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
