// Code generated by Kitex v0.16.2. DO NOT EDIT.

package catalogadminservice

import (
	"context"
	v1 "github.com/asherzj/financial_configuration_center/kitex_gen/finconfig/control/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateCollection(ctx context.Context, Req *v1.CreateCollectionRequest, callOptions ...callopt.Option) (r *v1.CreateCollectionResponse, err error)
	UpdateCollection(ctx context.Context, Req *v1.UpdateCollectionRequest, callOptions ...callopt.Option) (r *v1.UpdateCollectionResponse, err error)
	GetCollection(ctx context.Context, Req *v1.GetCollectionRequest, callOptions ...callopt.Option) (r *v1.GetCollectionResponse, err error)
	ListCollections(ctx context.Context, Req *v1.ListCollectionsRequest, callOptions ...callopt.Option) (r *v1.ListCollectionsResponse, err error)
	CreateSubscription(ctx context.Context, Req *v1.CreateSubscriptionRequest, callOptions ...callopt.Option) (r *v1.CreateSubscriptionResponse, err error)
	UpdateSubscription(ctx context.Context, Req *v1.UpdateSubscriptionRequest, callOptions ...callopt.Option) (r *v1.UpdateSubscriptionResponse, err error)
	ListSubscriptions(ctx context.Context, Req *v1.ListSubscriptionsRequest, callOptions ...callopt.Option) (r *v1.ListSubscriptionsResponse, err error)
	CreateModel(ctx context.Context, Req *v1.CreateModelRequest, callOptions ...callopt.Option) (r *v1.CreateModelResponse, err error)
	UpdateModel(ctx context.Context, Req *v1.UpdateModelRequest, callOptions ...callopt.Option) (r *v1.UpdateModelResponse, err error)
	GetModel(ctx context.Context, Req *v1.GetModelRequest, callOptions ...callopt.Option) (r *v1.GetModelResponse, err error)
	ListModels(ctx context.Context, Req *v1.ListModelsRequest, callOptions ...callopt.Option) (r *v1.ListModelsResponse, err error)
	CreateReleaseTemplate(ctx context.Context, Req *v1.CreateReleaseTemplateRequest, callOptions ...callopt.Option) (r *v1.CreateReleaseTemplateResponse, err error)
	GetReleaseTemplate(ctx context.Context, Req *v1.GetReleaseTemplateRequest, callOptions ...callopt.Option) (r *v1.GetReleaseTemplateResponse, err error)
	ListReleaseTemplates(ctx context.Context, Req *v1.ListReleaseTemplatesRequest, callOptions ...callopt.Option) (r *v1.ListReleaseTemplatesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCatalogAdminServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCatalogAdminServiceClient struct {
	*kClient
}

func (p *kCatalogAdminServiceClient) CreateCollection(ctx context.Context, Req *v1.CreateCollectionRequest, callOptions ...callopt.Option) (r *v1.CreateCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCollection(ctx, Req)
}

func (p *kCatalogAdminServiceClient) UpdateCollection(ctx context.Context, Req *v1.UpdateCollectionRequest, callOptions ...callopt.Option) (r *v1.UpdateCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateCollection(ctx, Req)
}

func (p *kCatalogAdminServiceClient) GetCollection(ctx context.Context, Req *v1.GetCollectionRequest, callOptions ...callopt.Option) (r *v1.GetCollectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCollection(ctx, Req)
}

func (p *kCatalogAdminServiceClient) ListCollections(ctx context.Context, Req *v1.ListCollectionsRequest, callOptions ...callopt.Option) (r *v1.ListCollectionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListCollections(ctx, Req)
}

func (p *kCatalogAdminServiceClient) CreateSubscription(ctx context.Context, Req *v1.CreateSubscriptionRequest, callOptions ...callopt.Option) (r *v1.CreateSubscriptionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSubscription(ctx, Req)
}

func (p *kCatalogAdminServiceClient) UpdateSubscription(ctx context.Context, Req *v1.UpdateSubscriptionRequest, callOptions ...callopt.Option) (r *v1.UpdateSubscriptionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateSubscription(ctx, Req)
}

func (p *kCatalogAdminServiceClient) ListSubscriptions(ctx context.Context, Req *v1.ListSubscriptionsRequest, callOptions ...callopt.Option) (r *v1.ListSubscriptionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSubscriptions(ctx, Req)
}

func (p *kCatalogAdminServiceClient) CreateModel(ctx context.Context, Req *v1.CreateModelRequest, callOptions ...callopt.Option) (r *v1.CreateModelResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateModel(ctx, Req)
}

func (p *kCatalogAdminServiceClient) UpdateModel(ctx context.Context, Req *v1.UpdateModelRequest, callOptions ...callopt.Option) (r *v1.UpdateModelResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateModel(ctx, Req)
}

func (p *kCatalogAdminServiceClient) GetModel(ctx context.Context, Req *v1.GetModelRequest, callOptions ...callopt.Option) (r *v1.GetModelResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetModel(ctx, Req)
}

func (p *kCatalogAdminServiceClient) ListModels(ctx context.Context, Req *v1.ListModelsRequest, callOptions ...callopt.Option) (r *v1.ListModelsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListModels(ctx, Req)
}

func (p *kCatalogAdminServiceClient) CreateReleaseTemplate(ctx context.Context, Req *v1.CreateReleaseTemplateRequest, callOptions ...callopt.Option) (r *v1.CreateReleaseTemplateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateReleaseTemplate(ctx, Req)
}

func (p *kCatalogAdminServiceClient) GetReleaseTemplate(ctx context.Context, Req *v1.GetReleaseTemplateRequest, callOptions ...callopt.Option) (r *v1.GetReleaseTemplateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetReleaseTemplate(ctx, Req)
}

func (p *kCatalogAdminServiceClient) ListReleaseTemplates(ctx context.Context, Req *v1.ListReleaseTemplatesRequest, callOptions ...callopt.Option) (r *v1.ListReleaseTemplatesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListReleaseTemplates(ctx, Req)
}
