// Code generated by Kitex v0.16.2. DO NOT EDIT.

package auditservice

import (
	"context"
	"errors"
	v1 "github.com/asherzj/financial_configuration_center/contracts/kitex_gen/finconfig/control/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListAuditRecords": kitex.NewMethodInfo(
		listAuditRecordsHandler,
		newListAuditRecordsArgs,
		newListAuditRecordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	auditServiceServiceInfo                = NewServiceInfo()
	auditServiceServiceInfoForClient       = NewServiceInfoForClient()
	auditServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return auditServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return auditServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return auditServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AuditService"
	handlerType := (*v1.AuditService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finconfig.control.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func listAuditRecordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListAuditRecordsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.AuditService).ListAuditRecords(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListAuditRecordsArgs:
		success, err := handler.(v1.AuditService).ListAuditRecords(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListAuditRecordsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListAuditRecordsArgs() interface{} {
	return &ListAuditRecordsArgs{}
}

func newListAuditRecordsResult() interface{} {
	return &ListAuditRecordsResult{}
}

type ListAuditRecordsArgs struct {
	Req *v1.ListAuditRecordsRequest
}

func (p *ListAuditRecordsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListAuditRecordsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListAuditRecordsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListAuditRecordsArgs_Req_DEFAULT *v1.ListAuditRecordsRequest

func (p *ListAuditRecordsArgs) GetReq() *v1.ListAuditRecordsRequest {
	if !p.IsSetReq() {
		return ListAuditRecordsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListAuditRecordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListAuditRecordsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListAuditRecordsResult struct {
	Success *v1.ListAuditRecordsResponse
}

var ListAuditRecordsResult_Success_DEFAULT *v1.ListAuditRecordsResponse

func (p *ListAuditRecordsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListAuditRecordsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListAuditRecordsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListAuditRecordsResult) GetSuccess() *v1.ListAuditRecordsResponse {
	if !p.IsSetSuccess() {
		return ListAuditRecordsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListAuditRecordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListAuditRecordsResponse)
}

func (p *ListAuditRecordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListAuditRecordsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListAuditRecords(ctx context.Context, Req *v1.ListAuditRecordsRequest) (r *v1.ListAuditRecordsResponse, err error) {
	var _args ListAuditRecordsArgs
	_args.Req = Req
	var _result ListAuditRecordsResult
	if err = p.c.Call(ctx, "ListAuditRecords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
