// Code generated by Kitex v0.16.2. DO NOT EDIT.

package releaseservice

import (
	"context"
	"errors"
	v1 "github.com/asherzj/financial_configuration_center/contracts/kitex_gen/finconfig/control/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateReleaseOrder": kitex.NewMethodInfo(
		createReleaseOrderHandler,
		newCreateReleaseOrderArgs,
		newCreateReleaseOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetReleaseOrder": kitex.NewMethodInfo(
		getReleaseOrderHandler,
		newGetReleaseOrderArgs,
		newGetReleaseOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListReleaseOrders": kitex.NewMethodInfo(
		listReleaseOrdersHandler,
		newListReleaseOrdersArgs,
		newListReleaseOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ActOnReleaseOrder": kitex.NewMethodInfo(
		actOnReleaseOrderHandler,
		newActOnReleaseOrderArgs,
		newActOnReleaseOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateCompensatingRelease": kitex.NewMethodInfo(
		createCompensatingReleaseHandler,
		newCreateCompensatingReleaseArgs,
		newCreateCompensatingReleaseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	releaseServiceServiceInfo                = NewServiceInfo()
	releaseServiceServiceInfoForClient       = NewServiceInfoForClient()
	releaseServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return releaseServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return releaseServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return releaseServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ReleaseService"
	handlerType := (*v1.ReleaseService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finconfig.control.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createReleaseOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateReleaseOrderRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.ReleaseService).CreateReleaseOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateReleaseOrderArgs:
		success, err := handler.(v1.ReleaseService).CreateReleaseOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateReleaseOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateReleaseOrderArgs() interface{} {
	return &CreateReleaseOrderArgs{}
}

func newCreateReleaseOrderResult() interface{} {
	return &CreateReleaseOrderResult{}
}

type CreateReleaseOrderArgs struct {
	Req *v1.CreateReleaseOrderRequest
}

func (p *CreateReleaseOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateReleaseOrderArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateReleaseOrderRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateReleaseOrderArgs_Req_DEFAULT *v1.CreateReleaseOrderRequest

func (p *CreateReleaseOrderArgs) GetReq() *v1.CreateReleaseOrderRequest {
	if !p.IsSetReq() {
		return CreateReleaseOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateReleaseOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateReleaseOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateReleaseOrderResult struct {
	Success *v1.CreateReleaseOrderResponse
}

var CreateReleaseOrderResult_Success_DEFAULT *v1.CreateReleaseOrderResponse

func (p *CreateReleaseOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateReleaseOrderResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateReleaseOrderResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateReleaseOrderResult) GetSuccess() *v1.CreateReleaseOrderResponse {
	if !p.IsSetSuccess() {
		return CreateReleaseOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateReleaseOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateReleaseOrderResponse)
}

func (p *CreateReleaseOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateReleaseOrderResult) GetResult() interface{} {
	return p.Success
}

func getReleaseOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetReleaseOrderRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.ReleaseService).GetReleaseOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetReleaseOrderArgs:
		success, err := handler.(v1.ReleaseService).GetReleaseOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetReleaseOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetReleaseOrderArgs() interface{} {
	return &GetReleaseOrderArgs{}
}

func newGetReleaseOrderResult() interface{} {
	return &GetReleaseOrderResult{}
}

type GetReleaseOrderArgs struct {
	Req *v1.GetReleaseOrderRequest
}

func (p *GetReleaseOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetReleaseOrderArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetReleaseOrderRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetReleaseOrderArgs_Req_DEFAULT *v1.GetReleaseOrderRequest

func (p *GetReleaseOrderArgs) GetReq() *v1.GetReleaseOrderRequest {
	if !p.IsSetReq() {
		return GetReleaseOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetReleaseOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetReleaseOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetReleaseOrderResult struct {
	Success *v1.GetReleaseOrderResponse
}

var GetReleaseOrderResult_Success_DEFAULT *v1.GetReleaseOrderResponse

func (p *GetReleaseOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetReleaseOrderResult) Unmarshal(in []byte) error {
	msg := new(v1.GetReleaseOrderResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetReleaseOrderResult) GetSuccess() *v1.GetReleaseOrderResponse {
	if !p.IsSetSuccess() {
		return GetReleaseOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetReleaseOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetReleaseOrderResponse)
}

func (p *GetReleaseOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetReleaseOrderResult) GetResult() interface{} {
	return p.Success
}

func listReleaseOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListReleaseOrdersRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.ReleaseService).ListReleaseOrders(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListReleaseOrdersArgs:
		success, err := handler.(v1.ReleaseService).ListReleaseOrders(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListReleaseOrdersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListReleaseOrdersArgs() interface{} {
	return &ListReleaseOrdersArgs{}
}

func newListReleaseOrdersResult() interface{} {
	return &ListReleaseOrdersResult{}
}

type ListReleaseOrdersArgs struct {
	Req *v1.ListReleaseOrdersRequest
}

func (p *ListReleaseOrdersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListReleaseOrdersArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListReleaseOrdersRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListReleaseOrdersArgs_Req_DEFAULT *v1.ListReleaseOrdersRequest

func (p *ListReleaseOrdersArgs) GetReq() *v1.ListReleaseOrdersRequest {
	if !p.IsSetReq() {
		return ListReleaseOrdersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListReleaseOrdersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListReleaseOrdersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListReleaseOrdersResult struct {
	Success *v1.ListReleaseOrdersResponse
}

var ListReleaseOrdersResult_Success_DEFAULT *v1.ListReleaseOrdersResponse

func (p *ListReleaseOrdersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListReleaseOrdersResult) Unmarshal(in []byte) error {
	msg := new(v1.ListReleaseOrdersResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListReleaseOrdersResult) GetSuccess() *v1.ListReleaseOrdersResponse {
	if !p.IsSetSuccess() {
		return ListReleaseOrdersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListReleaseOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListReleaseOrdersResponse)
}

func (p *ListReleaseOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListReleaseOrdersResult) GetResult() interface{} {
	return p.Success
}

func actOnReleaseOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ActOnReleaseOrderRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.ReleaseService).ActOnReleaseOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ActOnReleaseOrderArgs:
		success, err := handler.(v1.ReleaseService).ActOnReleaseOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ActOnReleaseOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newActOnReleaseOrderArgs() interface{} {
	return &ActOnReleaseOrderArgs{}
}

func newActOnReleaseOrderResult() interface{} {
	return &ActOnReleaseOrderResult{}
}

type ActOnReleaseOrderArgs struct {
	Req *v1.ActOnReleaseOrderRequest
}

func (p *ActOnReleaseOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ActOnReleaseOrderArgs) Unmarshal(in []byte) error {
	msg := new(v1.ActOnReleaseOrderRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ActOnReleaseOrderArgs_Req_DEFAULT *v1.ActOnReleaseOrderRequest

func (p *ActOnReleaseOrderArgs) GetReq() *v1.ActOnReleaseOrderRequest {
	if !p.IsSetReq() {
		return ActOnReleaseOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ActOnReleaseOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ActOnReleaseOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ActOnReleaseOrderResult struct {
	Success *v1.ActOnReleaseOrderResponse
}

var ActOnReleaseOrderResult_Success_DEFAULT *v1.ActOnReleaseOrderResponse

func (p *ActOnReleaseOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ActOnReleaseOrderResult) Unmarshal(in []byte) error {
	msg := new(v1.ActOnReleaseOrderResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ActOnReleaseOrderResult) GetSuccess() *v1.ActOnReleaseOrderResponse {
	if !p.IsSetSuccess() {
		return ActOnReleaseOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ActOnReleaseOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ActOnReleaseOrderResponse)
}

func (p *ActOnReleaseOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ActOnReleaseOrderResult) GetResult() interface{} {
	return p.Success
}

func createCompensatingReleaseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateCompensatingReleaseRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.ReleaseService).CreateCompensatingRelease(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateCompensatingReleaseArgs:
		success, err := handler.(v1.ReleaseService).CreateCompensatingRelease(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateCompensatingReleaseResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateCompensatingReleaseArgs() interface{} {
	return &CreateCompensatingReleaseArgs{}
}

func newCreateCompensatingReleaseResult() interface{} {
	return &CreateCompensatingReleaseResult{}
}

type CreateCompensatingReleaseArgs struct {
	Req *v1.CreateCompensatingReleaseRequest
}

func (p *CreateCompensatingReleaseArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateCompensatingReleaseArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateCompensatingReleaseRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateCompensatingReleaseArgs_Req_DEFAULT *v1.CreateCompensatingReleaseRequest

func (p *CreateCompensatingReleaseArgs) GetReq() *v1.CreateCompensatingReleaseRequest {
	if !p.IsSetReq() {
		return CreateCompensatingReleaseArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateCompensatingReleaseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateCompensatingReleaseArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateCompensatingReleaseResult struct {
	Success *v1.CreateCompensatingReleaseResponse
}

var CreateCompensatingReleaseResult_Success_DEFAULT *v1.CreateCompensatingReleaseResponse

func (p *CreateCompensatingReleaseResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateCompensatingReleaseResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateCompensatingReleaseResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateCompensatingReleaseResult) GetSuccess() *v1.CreateCompensatingReleaseResponse {
	if !p.IsSetSuccess() {
		return CreateCompensatingReleaseResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateCompensatingReleaseResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateCompensatingReleaseResponse)
}

func (p *CreateCompensatingReleaseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateCompensatingReleaseResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateReleaseOrder(ctx context.Context, Req *v1.CreateReleaseOrderRequest) (r *v1.CreateReleaseOrderResponse, err error) {
	var _args CreateReleaseOrderArgs
	_args.Req = Req
	var _result CreateReleaseOrderResult
	if err = p.c.Call(ctx, "CreateReleaseOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetReleaseOrder(ctx context.Context, Req *v1.GetReleaseOrderRequest) (r *v1.GetReleaseOrderResponse, err error) {
	var _args GetReleaseOrderArgs
	_args.Req = Req
	var _result GetReleaseOrderResult
	if err = p.c.Call(ctx, "GetReleaseOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListReleaseOrders(ctx context.Context, Req *v1.ListReleaseOrdersRequest) (r *v1.ListReleaseOrdersResponse, err error) {
	var _args ListReleaseOrdersArgs
	_args.Req = Req
	var _result ListReleaseOrdersResult
	if err = p.c.Call(ctx, "ListReleaseOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ActOnReleaseOrder(ctx context.Context, Req *v1.ActOnReleaseOrderRequest) (r *v1.ActOnReleaseOrderResponse, err error) {
	var _args ActOnReleaseOrderArgs
	_args.Req = Req
	var _result ActOnReleaseOrderResult
	if err = p.c.Call(ctx, "ActOnReleaseOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateCompensatingRelease(ctx context.Context, Req *v1.CreateCompensatingReleaseRequest) (r *v1.CreateCompensatingReleaseResponse, err error) {
	var _args CreateCompensatingReleaseArgs
	_args.Req = Req
	var _result CreateCompensatingReleaseResult
	if err = p.c.Call(ctx, "CreateCompensatingRelease", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
