// Code generated by Kitex v0.16.2. DO NOT EDIT.

package diagnosticsservice

import (
	"context"
	"errors"
	v1 "github.com/asherzj/financial_configuration_center/kitex_gen/finconfig/config/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetSnapshotStatus": kitex.NewMethodInfo(
		getSnapshotStatusHandler,
		newGetSnapshotStatusArgs,
		newGetSnapshotStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetCollectionStatus": kitex.NewMethodInfo(
		getCollectionStatusHandler,
		newGetCollectionStatusArgs,
		newGetCollectionStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	diagnosticsServiceServiceInfo                = NewServiceInfo()
	diagnosticsServiceServiceInfoForClient       = NewServiceInfoForClient()
	diagnosticsServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return diagnosticsServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return diagnosticsServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return diagnosticsServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DiagnosticsService"
	handlerType := (*v1.DiagnosticsService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finconfig.config.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func getSnapshotStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetSnapshotStatusRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.DiagnosticsService).GetSnapshotStatus(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetSnapshotStatusArgs:
		success, err := handler.(v1.DiagnosticsService).GetSnapshotStatus(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetSnapshotStatusResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetSnapshotStatusArgs() interface{} {
	return &GetSnapshotStatusArgs{}
}

func newGetSnapshotStatusResult() interface{} {
	return &GetSnapshotStatusResult{}
}

type GetSnapshotStatusArgs struct {
	Req *v1.GetSnapshotStatusRequest
}

func (p *GetSnapshotStatusArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetSnapshotStatusArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetSnapshotStatusRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetSnapshotStatusArgs_Req_DEFAULT *v1.GetSnapshotStatusRequest

func (p *GetSnapshotStatusArgs) GetReq() *v1.GetSnapshotStatusRequest {
	if !p.IsSetReq() {
		return GetSnapshotStatusArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetSnapshotStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetSnapshotStatusArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetSnapshotStatusResult struct {
	Success *v1.GetSnapshotStatusResponse
}

var GetSnapshotStatusResult_Success_DEFAULT *v1.GetSnapshotStatusResponse

func (p *GetSnapshotStatusResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetSnapshotStatusResult) Unmarshal(in []byte) error {
	msg := new(v1.GetSnapshotStatusResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetSnapshotStatusResult) GetSuccess() *v1.GetSnapshotStatusResponse {
	if !p.IsSetSuccess() {
		return GetSnapshotStatusResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetSnapshotStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetSnapshotStatusResponse)
}

func (p *GetSnapshotStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetSnapshotStatusResult) GetResult() interface{} {
	return p.Success
}

func getCollectionStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetCollectionStatusRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.DiagnosticsService).GetCollectionStatus(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetCollectionStatusArgs:
		success, err := handler.(v1.DiagnosticsService).GetCollectionStatus(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCollectionStatusResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetCollectionStatusArgs() interface{} {
	return &GetCollectionStatusArgs{}
}

func newGetCollectionStatusResult() interface{} {
	return &GetCollectionStatusResult{}
}

type GetCollectionStatusArgs struct {
	Req *v1.GetCollectionStatusRequest
}

func (p *GetCollectionStatusArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetCollectionStatusArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetCollectionStatusRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCollectionStatusArgs_Req_DEFAULT *v1.GetCollectionStatusRequest

func (p *GetCollectionStatusArgs) GetReq() *v1.GetCollectionStatusRequest {
	if !p.IsSetReq() {
		return GetCollectionStatusArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCollectionStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCollectionStatusArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCollectionStatusResult struct {
	Success *v1.GetCollectionStatusResponse
}

var GetCollectionStatusResult_Success_DEFAULT *v1.GetCollectionStatusResponse

func (p *GetCollectionStatusResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetCollectionStatusResult) Unmarshal(in []byte) error {
	msg := new(v1.GetCollectionStatusResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCollectionStatusResult) GetSuccess() *v1.GetCollectionStatusResponse {
	if !p.IsSetSuccess() {
		return GetCollectionStatusResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCollectionStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetCollectionStatusResponse)
}

func (p *GetCollectionStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCollectionStatusResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetSnapshotStatus(ctx context.Context, Req *v1.GetSnapshotStatusRequest) (r *v1.GetSnapshotStatusResponse, err error) {
	var _args GetSnapshotStatusArgs
	_args.Req = Req
	var _result GetSnapshotStatusResult
	if err = p.c.Call(ctx, "GetSnapshotStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCollectionStatus(ctx context.Context, Req *v1.GetCollectionStatusRequest) (r *v1.GetCollectionStatusResponse, err error) {
	var _args GetCollectionStatusArgs
	_args.Req = Req
	var _result GetCollectionStatusResult
	if err = p.c.Call(ctx, "GetCollectionStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
