// Code generated by Kitex v0.16.2. DO NOT EDIT.

package operationsservice

import (
	"context"
	"errors"
	v1 "github.com/asherzj/financial_configuration_center/contracts/kitex_gen/finconfig/control/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListOutboxEvents": kitex.NewMethodInfo(
		listOutboxEventsHandler,
		newListOutboxEventsArgs,
		newListOutboxEventsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ReplayOutboxEvent": kitex.NewMethodInfo(
		replayOutboxEventHandler,
		newReplayOutboxEventArgs,
		newReplayOutboxEventResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	operationsServiceServiceInfo                = NewServiceInfo()
	operationsServiceServiceInfoForClient       = NewServiceInfoForClient()
	operationsServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return operationsServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return operationsServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return operationsServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OperationsService"
	handlerType := (*v1.OperationsService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finconfig.control.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func listOutboxEventsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListOutboxEventsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.OperationsService).ListOutboxEvents(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListOutboxEventsArgs:
		success, err := handler.(v1.OperationsService).ListOutboxEvents(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListOutboxEventsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListOutboxEventsArgs() interface{} {
	return &ListOutboxEventsArgs{}
}

func newListOutboxEventsResult() interface{} {
	return &ListOutboxEventsResult{}
}

type ListOutboxEventsArgs struct {
	Req *v1.ListOutboxEventsRequest
}

func (p *ListOutboxEventsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListOutboxEventsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListOutboxEventsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListOutboxEventsArgs_Req_DEFAULT *v1.ListOutboxEventsRequest

func (p *ListOutboxEventsArgs) GetReq() *v1.ListOutboxEventsRequest {
	if !p.IsSetReq() {
		return ListOutboxEventsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListOutboxEventsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListOutboxEventsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListOutboxEventsResult struct {
	Success *v1.ListOutboxEventsResponse
}

var ListOutboxEventsResult_Success_DEFAULT *v1.ListOutboxEventsResponse

func (p *ListOutboxEventsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListOutboxEventsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListOutboxEventsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListOutboxEventsResult) GetSuccess() *v1.ListOutboxEventsResponse {
	if !p.IsSetSuccess() {
		return ListOutboxEventsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListOutboxEventsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListOutboxEventsResponse)
}

func (p *ListOutboxEventsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListOutboxEventsResult) GetResult() interface{} {
	return p.Success
}

func replayOutboxEventHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ReplayOutboxEventRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.OperationsService).ReplayOutboxEvent(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ReplayOutboxEventArgs:
		success, err := handler.(v1.OperationsService).ReplayOutboxEvent(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ReplayOutboxEventResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newReplayOutboxEventArgs() interface{} {
	return &ReplayOutboxEventArgs{}
}

func newReplayOutboxEventResult() interface{} {
	return &ReplayOutboxEventResult{}
}

type ReplayOutboxEventArgs struct {
	Req *v1.ReplayOutboxEventRequest
}

func (p *ReplayOutboxEventArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ReplayOutboxEventArgs) Unmarshal(in []byte) error {
	msg := new(v1.ReplayOutboxEventRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ReplayOutboxEventArgs_Req_DEFAULT *v1.ReplayOutboxEventRequest

func (p *ReplayOutboxEventArgs) GetReq() *v1.ReplayOutboxEventRequest {
	if !p.IsSetReq() {
		return ReplayOutboxEventArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ReplayOutboxEventArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ReplayOutboxEventArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ReplayOutboxEventResult struct {
	Success *v1.ReplayOutboxEventResponse
}

var ReplayOutboxEventResult_Success_DEFAULT *v1.ReplayOutboxEventResponse

func (p *ReplayOutboxEventResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ReplayOutboxEventResult) Unmarshal(in []byte) error {
	msg := new(v1.ReplayOutboxEventResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ReplayOutboxEventResult) GetSuccess() *v1.ReplayOutboxEventResponse {
	if !p.IsSetSuccess() {
		return ReplayOutboxEventResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ReplayOutboxEventResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ReplayOutboxEventResponse)
}

func (p *ReplayOutboxEventResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ReplayOutboxEventResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListOutboxEvents(ctx context.Context, Req *v1.ListOutboxEventsRequest) (r *v1.ListOutboxEventsResponse, err error) {
	var _args ListOutboxEventsArgs
	_args.Req = Req
	var _result ListOutboxEventsResult
	if err = p.c.Call(ctx, "ListOutboxEvents", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReplayOutboxEvent(ctx context.Context, Req *v1.ReplayOutboxEventRequest) (r *v1.ReplayOutboxEventResponse, err error) {
	var _args ReplayOutboxEventArgs
	_args.Req = Req
	var _result ReplayOutboxEventResult
	if err = p.c.Call(ctx, "ReplayOutboxEvent", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
