// Code generated by Kitex v0.16.2. DO NOT EDIT.
package operationsservice

import (
	v1 "github.com/asherzj/financial_configuration_center/contracts/kitex_gen/finconfig/control/v1"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler v1.OperationsService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler v1.OperationsService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
