/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["queryPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCollections"];
        put?: never;
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        get: operations["getCollection"];
        put: operations["updateCollection"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSubscriptions"];
        put?: never;
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModels"];
        put?: never;
        post: operations["createModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReleaseTemplates"];
        put?: never;
        post: operations["createReleaseTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReleaseOrders"];
        put?: never;
        post: operations["createReleaseOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReleaseID"];
            };
            cookie?: never;
        };
        get: operations["getReleaseOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{id}/actions": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ReleaseID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["actOnReleaseOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{id}/compensations": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ReleaseID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCompensatingRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensitive-fields/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revealSensitiveField"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSnapshotDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/collections/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCollectionDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOutboxEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox-events/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replayOutboxEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Scope: {
            region: string;
            environment: string;
            stage?: string;
        };
        SnapshotIdentity: {
            /** Format: uuid */
            serverEpoch: string;
            /** Format: uuid */
            serverInstanceId: string;
            /** Format: uuid */
            snapshotInstance: string;
            /** Format: int64 */
            snapshotGeneration: number;
        };
        SnapshotDiagnostics: {
            snapshot: {
                serverEpoch: string;
                serverInstanceId: string;
                snapshotInstance: string;
                /** Format: int64 */
                generation: number;
                /** Format: date-time */
                publishedAt: string;
            };
            environment: string;
            collections: {
                name: string;
                /** Format: int64 */
                revision: number;
                digest: {
                    algorithm: string;
                    value: string;
                };
            }[];
            failedDependencyGroups: string[][];
            lastErrorCode: string;
        };
        Session: {
            subject: string;
            displayName: string;
            roles: string[];
            scopes: components["schemas"]["Scope"][];
            /** Format: date-time */
            expiresAt: string;
        };
        Collection: {
            name: string;
            description?: string;
            fields: Record<string, never>[];
            keyFields: string[];
            sdkDeliveryEnabled: boolean;
            /** Format: int64 */
            schemaVersion: number;
            /** @enum {string} */
            status: "ENABLED" | "DISABLED";
            /** Format: int64 */
            configRevision: number;
        };
        QueryPageRequest: {
            modelCode: string;
            scope: components["schemas"]["Scope"];
            /** @enum {string} */
            queryType: "ALL" | "ONLY_DATA";
            conditions?: components["schemas"]["FilterCondition"][];
            pageNumber?: number;
            pageSize?: number;
            previewBucket?: number;
        };
        QueryPageResponse: {
            modelCode: string;
            rows: components["schemas"]["PageRow"][];
            projectionFields: string[];
            interactionFields: Record<string, never>[];
            releaseTypes: components["schemas"]["ReleaseTypeMetadata"][];
            snapshot: components["schemas"]["SnapshotIdentity"];
        };
        FilterCondition: {
            field: string;
            /** @enum {string} */
            operator: "EXACT" | "CONTAINS" | "CLOSED_RANGE" | "OPEN_RANGE" | "IN" | "NOT_IN";
            value?: string;
            lower?: string;
            upper?: string;
            set?: string[];
        };
        PageRow: {
            recordKey: string;
            /** Format: int64 */
            recordRevision: number;
            values: {
                [key: string]: string;
            };
            maskedFields: string[];
            basePresent: boolean;
            baseValues: {
                [key: string]: string;
            };
            changedFields: string[];
        };
        ReleaseTypeMetadata: {
            code: string;
            name: string;
            templateCode: string;
            available: boolean;
            unavailableReasonCode?: string;
        };
        ReleaseItemInput: {
            /** @enum {string} */
            action: "ADD" | "MODIFY" | "DELETE";
            baseBefore: {
                [key: string]: string;
            };
            effectiveBefore: {
                [key: string]: string;
            };
            after: {
                [key: string]: string;
            };
            /** Format: int64 */
            expectedRecordRevision: number;
            /** Format: int64 */
            expectedCollectionRevision: number;
            preserveSensitiveFields?: string[];
        };
        CreateReleaseOrder: {
            modelCode: string;
            releaseTypeCode: string;
            scope: components["schemas"]["Scope"];
            description: string;
            items: components["schemas"]["ReleaseItemInput"][];
            /** Format: date-time */
            effectiveFrom?: string;
            /** Format: date-time */
            effectiveUntil?: string;
        };
        ReleaseActionRequest: {
            /** @enum {string} */
            action: "EXECUTE" | "ADVANCE" | "ROLLBACK" | "APPROVE" | "REJECT";
            /** Format: int64 */
            expectedOrderRevision: number;
            expectedCurrentStep: string;
            comment?: string;
        };
        CreateCompensatingRelease: {
            description: string;
        };
        OutboxEvent: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            sequenceNo: number;
            eventType: string;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "SENT" | "DEAD_LETTER";
            /** Format: int64 */
            leaseRevision: number;
            attempts: number;
            /** Format: date-time */
            nextAttemptAt: string;
            lastError?: string;
        };
        OutboxEventPage: {
            events: components["schemas"]["OutboxEvent"][];
            page: {
                number: number;
                size: number;
                /** Format: int64 */
                totalNumber: number;
                totalPages: number;
            };
        };
        ReplayOutboxEvent: {
            /** Format: int64 */
            expectedEventRevision: number;
            reason: string;
            confirmation: string;
        };
        ReleaseOrderDetail: {
            order: {
                id: string;
                description?: string;
                compensatesOrderId?: string;
                canCompensate?: boolean;
                /** @enum {string} */
                status: "IN_PROGRESS" | "SUCCEEDED" | "REJECTED" | "ROLLED_BACK";
                /** @description Stable step code from the template snapshot. */
                currentStep: string;
                /** @enum {string} */
                currentStepType: "MANUAL_REVIEW" | "OVERLAY_APPLY" | "PERCENT_ROLLOUT" | "BASE_APPLY" | "COMPARE" | "COMPLETE";
                /** @enum {string} */
                currentStepStatus: "PENDING" | "EXECUTING" | "EXECUTED" | "APPROVED" | "REJECTED" | "ROLLED_BACK";
                /** Format: int64 */
                entityRevision: number;
            };
            items: Record<string, never>[];
            steps: {
                code: string;
                type: string;
                status: string;
                rolloutRanges?: {
                    start: number;
                    end: number;
                }[];
                compareResult?: {
                    expectedDigest: {
                        algorithm: string;
                        value: string;
                    };
                    actualDigest: {
                        algorithm: string;
                        value: string;
                    };
                    diffKeys: string[];
                    /** Format: date-time */
                    checkedAt: string;
                };
            }[];
            allowedActions: ("EXECUTE" | "ADVANCE" | "ROLLBACK" | "APPROVE" | "REJECT")[];
        };
        RevealFieldRequest: {
            modelCode: string;
            scope: components["schemas"]["Scope"];
            recordKey: string;
            fieldName: string;
            /** Format: int64 */
            expectedRecordRevision: number;
            /** Format: int64 */
            expectedCollectionRevision: number;
            /** Format: int64 */
            expectedModelRevision: number;
            /** Format: uuid */
            expectedServerEpoch: string;
            /** Format: uuid */
            expectedSnapshotInstance: string;
            /** Format: int64 */
            expectedSnapshotGeneration: number;
            reason: string;
            previewBucket?: number;
        };
        ErrorEnvelope: {
            code: string;
            message: string;
            field?: string;
            resourceType?: string;
            resourceId?: string;
            /** Format: int64 */
            currentRevision?: number;
            traceId: string;
        };
    };
    responses: {
        /** @description Stable error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CollectionName: string;
        ReleaseID: string;
        ExpectedRevision: number;
        IdempotencyKey: string;
        RequestID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    queryPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryPageRequest"];
            };
        };
        responses: {
            /** @description Page data and optional interaction metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryPageResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listCollections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"][];
                };
            };
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Collection"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateCollection: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["ExpectedRevision"];
            };
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Collection"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listReleaseTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createReleaseTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable template version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listReleaseOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createReleaseOrder: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleaseOrder"];
            };
        };
        responses: {
            /** @description Release order */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOrderDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getReleaseOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReleaseID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOrderDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    actOnReleaseOrder: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ReleaseID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseActionRequest"];
            };
        };
        responses: {
            /** @description Updated release detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOrderDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCompensatingRelease: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ReleaseID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompensatingRelease"];
            };
        };
        responses: {
            /** @description Compensation release created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOrderDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revealSensitiveField: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID": components["parameters"]["RequestID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealFieldRequest"];
            };
        };
        responses: {
            /** @description Ephemeral value; response is never cacheable */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        value: string;
                        /** Format: date-time */
                        expiresAt: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSnapshotDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot metadata without configuration values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDiagnostics"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCollectionDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["CollectionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection snapshot metadata without configuration values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listAuditRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Masked audit records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOutboxEvents: {
        parameters: {
            query?: {
                status?: "PENDING" | "PROCESSING" | "SENT" | "DEAD_LETTER";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Outbox metadata without event payloads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxEventPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    replayOutboxEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayOutboxEvent"];
            };
        };
        responses: {
            /** @description Replay scheduled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event: components["schemas"]["OutboxEvent"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
