// Code generated by Kitex v0.16.2. DO NOT EDIT.

package releaseservice

import (
	"context"
	v1 "github.com/asherzj/financial_configuration_center/kitex_gen/finconfig/control/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateReleaseOrder(ctx context.Context, Req *v1.CreateReleaseOrderRequest, callOptions ...callopt.Option) (r *v1.CreateReleaseOrderResponse, err error)
	GetReleaseOrder(ctx context.Context, Req *v1.GetReleaseOrderRequest, callOptions ...callopt.Option) (r *v1.GetReleaseOrderResponse, err error)
	ListReleaseOrders(ctx context.Context, Req *v1.ListReleaseOrdersRequest, callOptions ...callopt.Option) (r *v1.ListReleaseOrdersResponse, err error)
	ActOnReleaseOrder(ctx context.Context, Req *v1.ActOnReleaseOrderRequest, callOptions ...callopt.Option) (r *v1.ActOnReleaseOrderResponse, err error)
	CreateCompensatingRelease(ctx context.Context, Req *v1.CreateCompensatingReleaseRequest, callOptions ...callopt.Option) (r *v1.CreateCompensatingReleaseResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kReleaseServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kReleaseServiceClient struct {
	*kClient
}

func (p *kReleaseServiceClient) CreateReleaseOrder(ctx context.Context, Req *v1.CreateReleaseOrderRequest, callOptions ...callopt.Option) (r *v1.CreateReleaseOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateReleaseOrder(ctx, Req)
}

func (p *kReleaseServiceClient) GetReleaseOrder(ctx context.Context, Req *v1.GetReleaseOrderRequest, callOptions ...callopt.Option) (r *v1.GetReleaseOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetReleaseOrder(ctx, Req)
}

func (p *kReleaseServiceClient) ListReleaseOrders(ctx context.Context, Req *v1.ListReleaseOrdersRequest, callOptions ...callopt.Option) (r *v1.ListReleaseOrdersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListReleaseOrders(ctx, Req)
}

func (p *kReleaseServiceClient) ActOnReleaseOrder(ctx context.Context, Req *v1.ActOnReleaseOrderRequest, callOptions ...callopt.Option) (r *v1.ActOnReleaseOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ActOnReleaseOrder(ctx, Req)
}

func (p *kReleaseServiceClient) CreateCompensatingRelease(ctx context.Context, Req *v1.CreateCompensatingReleaseRequest, callOptions ...callopt.Option) (r *v1.CreateCompensatingReleaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCompensatingRelease(ctx, Req)
}
