package contracts_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestContractSpineSourcesExist(t *testing.T) {
	t.Parallel()

	required := []string{
		"api/proto/finconfig/common/v1/common.proto",
		"api/proto/finconfig/config/v1/config.proto",
		"api/proto/finconfig/control/v1/control.proto",
		"api/openapi/finconfig-admin-v1.yaml",
		"db/migrations/mysql/000001_finconfig_v1.sql",
		"buf.yaml",
		"buf.gen.yaml",
		"package.json",
		"pnpm-workspace.yaml",
		"web/admin-console/package.json",
		"web/admin-console/src/main.tsx",
		"web/admin-console/src/api/schema.d.ts",
	}

	root := repositoryRoot(t)
	for _, name := range required {
		if _, err := os.Stat(filepath.Join(root, name)); err != nil {
			t.Errorf("required contract source %s: %v", name, err)
		}
	}
}

func TestFrontendToolchainIsPinnedAndOpenAPIDriven(t *testing.T) {
	t.Parallel()

	root := repositoryRoot(t)
	b, err := os.ReadFile(filepath.Join(root, "package.json"))
	if err != nil {
		t.Fatal(err)
	}
	var manifest struct {
		PackageManager string `json:"packageManager"`
		Engines        struct {
			Node string `json:"node"`
		} `json:"engines"`
	}
	if err := json.Unmarshal(b, &manifest); err != nil {
		t.Fatalf("parse package.json: %v", err)
	}
	if manifest.PackageManager != "pnpm@11.4.0" {
		t.Fatalf("packageManager = %q, want pnpm@11.4.0", manifest.PackageManager)
	}
	if !strings.Contains(manifest.Engines.Node, "24") {
		t.Fatalf("Node engine %q does not include Node 24", manifest.Engines.Node)
	}

	assertContains(t, filepath.Join(root, "web/admin-console/package.json"),
		"openapi-typescript", "generate:api", "typecheck", "vitest")
	assertContains(t, filepath.Join(root, "web/admin-console/src/api/schema.d.ts"),
		"This file was auto-generated by openapi-typescript")
}

func TestContractsFreezeSemanticRevisionNames(t *testing.T) {
	t.Parallel()

	root := repositoryRoot(t)
	assertContains(t, filepath.Join(root, "api/proto/finconfig/common/v1/common.proto"),
		"server_epoch", "server_instance_id", "snapshot_generation")
	assertContains(t, filepath.Join(root, "api/proto/finconfig/control/v1/control.proto"),
		"expected_record_revision", "expected_collection_revision", "expected_order_revision", "action_request_id")
	assertContains(t, filepath.Join(root, "db/migrations/mysql/000001_finconfig_v1.sql"),
		"config_revision", "entity_revision", "lease_revision", "release_action_requests")
	assertContains(t, filepath.Join(root, "internal/platform/rpc/options.go"),
		"client.WithTransportProtocol(transport.GRPC)", "client.WithGRPCTLSConfig(configured)")
}

func TestAdminOpenAPIIsSelfContainedAndHasUniqueOperations(t *testing.T) {
	t.Parallel()

	path := filepath.Join(repositoryRoot(t), "api/openapi/finconfig-admin-v1.yaml")
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var document map[string]any
	if err := yaml.Unmarshal(b, &document); err != nil {
		t.Fatalf("parse OpenAPI: %v", err)
	}
	if got := document["openapi"]; got != "3.1.0" {
		t.Fatalf("openapi version = %v, want 3.1.0", got)
	}

	operationIDs := make(map[string]string)
	walkDocument(t, document, func(location string, value any) {
		object, ok := value.(map[string]any)
		if !ok {
			return
		}
		if operationID, ok := object["operationId"].(string); ok {
			if previous, duplicate := operationIDs[operationID]; duplicate {
				t.Errorf("duplicate operationId %q at %s and %s", operationID, previous, location)
			}
			operationIDs[operationID] = location
		}
		if ref, ok := object["$ref"].(string); ok {
			if !strings.HasPrefix(ref, "#/components/") {
				t.Errorf("external OpenAPI ref %q at %s", ref, location)
				return
			}
			if !openAPIRefExists(document, ref) {
				t.Errorf("unresolved OpenAPI ref %q at %s", ref, location)
			}
		}
	})
	if len(operationIDs) < 15 {
		t.Fatalf("operation count = %d, want at least 15", len(operationIDs))
	}
	paths := document["paths"].(map[string]any)
	for route := range paths {
		if strings.Contains(route, "/records") {
			t.Errorf("direct ConfigurationRecord route is forbidden: %s", route)
		}
	}
}

func walkDocument(t *testing.T, value any, visit func(string, any)) {
	t.Helper()
	var walk func(string, any)
	walk = func(location string, current any) {
		visit(location, current)
		switch typed := current.(type) {
		case map[string]any:
			for key, child := range typed {
				walk(location+"/"+key, child)
			}
		case []any:
			for index, child := range typed {
				walk(location+"/"+strconv.Itoa(index), child)
			}
		}
	}
	walk("#", value)
}

func openAPIRefExists(document map[string]any, ref string) bool {
	var current any = document
	for _, segment := range strings.Split(strings.TrimPrefix(ref, "#/"), "/") {
		object, ok := current.(map[string]any)
		if !ok {
			return false
		}
		current, ok = object[segment]
		if !ok {
			return false
		}
	}
	return current != nil
}

func repositoryRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("repository root not found")
		}
		dir = parent
	}
}

func assertContains(t *testing.T, path string, needles ...string) {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Errorf("read %s: %v", path, err)
		return
	}
	for _, needle := range needles {
		if !strings.Contains(string(b), needle) {
			t.Errorf("%s does not contain %q", path, needle)
		}
	}
}
