// Code generated by Kitex v0.16.2. DO NOT EDIT.

package pagequeryservice

import (
	"context"
	"errors"
	v1 "github.com/asherzj/financial_configuration_center/kitex_gen/finconfig/config/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"QueryPage": kitex.NewMethodInfo(
		queryPageHandler,
		newQueryPageArgs,
		newQueryPageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	pageQueryServiceServiceInfo                = NewServiceInfo()
	pageQueryServiceServiceInfoForClient       = NewServiceInfoForClient()
	pageQueryServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return pageQueryServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return pageQueryServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return pageQueryServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PageQueryService"
	handlerType := (*v1.PageQueryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finconfig.config.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func queryPageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.QueryPageRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.PageQueryService).QueryPage(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *QueryPageArgs:
		success, err := handler.(v1.PageQueryService).QueryPage(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryPageResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newQueryPageArgs() interface{} {
	return &QueryPageArgs{}
}

func newQueryPageResult() interface{} {
	return &QueryPageResult{}
}

type QueryPageArgs struct {
	Req *v1.QueryPageRequest
}

func (p *QueryPageArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *QueryPageArgs) Unmarshal(in []byte) error {
	msg := new(v1.QueryPageRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryPageArgs_Req_DEFAULT *v1.QueryPageRequest

func (p *QueryPageArgs) GetReq() *v1.QueryPageRequest {
	if !p.IsSetReq() {
		return QueryPageArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryPageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QueryPageArgs) GetFirstArgument() interface{} {
	return p.Req
}

type QueryPageResult struct {
	Success *v1.QueryPageResponse
}

var QueryPageResult_Success_DEFAULT *v1.QueryPageResponse

func (p *QueryPageResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *QueryPageResult) Unmarshal(in []byte) error {
	msg := new(v1.QueryPageResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryPageResult) GetSuccess() *v1.QueryPageResponse {
	if !p.IsSetSuccess() {
		return QueryPageResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryPageResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.QueryPageResponse)
}

func (p *QueryPageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QueryPageResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) QueryPage(ctx context.Context, Req *v1.QueryPageRequest) (r *v1.QueryPageResponse, err error) {
	var _args QueryPageArgs
	_args.Req = Req
	var _result QueryPageResult
	if err = p.c.Call(ctx, "QueryPage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
