// Code generated by Kitex v0.16.2. DO NOT EDIT.

package catalogadminservice

import (
	"context"
	"errors"
	v1 "github.com/asherzj/financial_configuration_center/contracts/kitex_gen/finconfig/control/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateCollection": kitex.NewMethodInfo(
		createCollectionHandler,
		newCreateCollectionArgs,
		newCreateCollectionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateCollection": kitex.NewMethodInfo(
		updateCollectionHandler,
		newUpdateCollectionArgs,
		newUpdateCollectionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetCollection": kitex.NewMethodInfo(
		getCollectionHandler,
		newGetCollectionArgs,
		newGetCollectionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListCollections": kitex.NewMethodInfo(
		listCollectionsHandler,
		newListCollectionsArgs,
		newListCollectionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateSubscription": kitex.NewMethodInfo(
		createSubscriptionHandler,
		newCreateSubscriptionArgs,
		newCreateSubscriptionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateSubscription": kitex.NewMethodInfo(
		updateSubscriptionHandler,
		newUpdateSubscriptionArgs,
		newUpdateSubscriptionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListSubscriptions": kitex.NewMethodInfo(
		listSubscriptionsHandler,
		newListSubscriptionsArgs,
		newListSubscriptionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateModel": kitex.NewMethodInfo(
		createModelHandler,
		newCreateModelArgs,
		newCreateModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateModel": kitex.NewMethodInfo(
		updateModelHandler,
		newUpdateModelArgs,
		newUpdateModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetModel": kitex.NewMethodInfo(
		getModelHandler,
		newGetModelArgs,
		newGetModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListModels": kitex.NewMethodInfo(
		listModelsHandler,
		newListModelsArgs,
		newListModelsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateReleaseTemplate": kitex.NewMethodInfo(
		createReleaseTemplateHandler,
		newCreateReleaseTemplateArgs,
		newCreateReleaseTemplateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetReleaseTemplate": kitex.NewMethodInfo(
		getReleaseTemplateHandler,
		newGetReleaseTemplateArgs,
		newGetReleaseTemplateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListReleaseTemplates": kitex.NewMethodInfo(
		listReleaseTemplatesHandler,
		newListReleaseTemplatesArgs,
		newListReleaseTemplatesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	catalogAdminServiceServiceInfo                = NewServiceInfo()
	catalogAdminServiceServiceInfoForClient       = NewServiceInfoForClient()
	catalogAdminServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return catalogAdminServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return catalogAdminServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return catalogAdminServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CatalogAdminService"
	handlerType := (*v1.CatalogAdminService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finconfig.control.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createCollectionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateCollectionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).CreateCollection(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateCollectionArgs:
		success, err := handler.(v1.CatalogAdminService).CreateCollection(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateCollectionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateCollectionArgs() interface{} {
	return &CreateCollectionArgs{}
}

func newCreateCollectionResult() interface{} {
	return &CreateCollectionResult{}
}

type CreateCollectionArgs struct {
	Req *v1.CreateCollectionRequest
}

func (p *CreateCollectionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateCollectionArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateCollectionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateCollectionArgs_Req_DEFAULT *v1.CreateCollectionRequest

func (p *CreateCollectionArgs) GetReq() *v1.CreateCollectionRequest {
	if !p.IsSetReq() {
		return CreateCollectionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateCollectionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateCollectionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateCollectionResult struct {
	Success *v1.CreateCollectionResponse
}

var CreateCollectionResult_Success_DEFAULT *v1.CreateCollectionResponse

func (p *CreateCollectionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateCollectionResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateCollectionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateCollectionResult) GetSuccess() *v1.CreateCollectionResponse {
	if !p.IsSetSuccess() {
		return CreateCollectionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateCollectionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateCollectionResponse)
}

func (p *CreateCollectionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateCollectionResult) GetResult() interface{} {
	return p.Success
}

func updateCollectionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdateCollectionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).UpdateCollection(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateCollectionArgs:
		success, err := handler.(v1.CatalogAdminService).UpdateCollection(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateCollectionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateCollectionArgs() interface{} {
	return &UpdateCollectionArgs{}
}

func newUpdateCollectionResult() interface{} {
	return &UpdateCollectionResult{}
}

type UpdateCollectionArgs struct {
	Req *v1.UpdateCollectionRequest
}

func (p *UpdateCollectionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateCollectionArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdateCollectionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateCollectionArgs_Req_DEFAULT *v1.UpdateCollectionRequest

func (p *UpdateCollectionArgs) GetReq() *v1.UpdateCollectionRequest {
	if !p.IsSetReq() {
		return UpdateCollectionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateCollectionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateCollectionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateCollectionResult struct {
	Success *v1.UpdateCollectionResponse
}

var UpdateCollectionResult_Success_DEFAULT *v1.UpdateCollectionResponse

func (p *UpdateCollectionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateCollectionResult) Unmarshal(in []byte) error {
	msg := new(v1.UpdateCollectionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateCollectionResult) GetSuccess() *v1.UpdateCollectionResponse {
	if !p.IsSetSuccess() {
		return UpdateCollectionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateCollectionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UpdateCollectionResponse)
}

func (p *UpdateCollectionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateCollectionResult) GetResult() interface{} {
	return p.Success
}

func getCollectionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetCollectionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).GetCollection(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetCollectionArgs:
		success, err := handler.(v1.CatalogAdminService).GetCollection(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCollectionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetCollectionArgs() interface{} {
	return &GetCollectionArgs{}
}

func newGetCollectionResult() interface{} {
	return &GetCollectionResult{}
}

type GetCollectionArgs struct {
	Req *v1.GetCollectionRequest
}

func (p *GetCollectionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetCollectionArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetCollectionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCollectionArgs_Req_DEFAULT *v1.GetCollectionRequest

func (p *GetCollectionArgs) GetReq() *v1.GetCollectionRequest {
	if !p.IsSetReq() {
		return GetCollectionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCollectionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCollectionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCollectionResult struct {
	Success *v1.GetCollectionResponse
}

var GetCollectionResult_Success_DEFAULT *v1.GetCollectionResponse

func (p *GetCollectionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetCollectionResult) Unmarshal(in []byte) error {
	msg := new(v1.GetCollectionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCollectionResult) GetSuccess() *v1.GetCollectionResponse {
	if !p.IsSetSuccess() {
		return GetCollectionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCollectionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetCollectionResponse)
}

func (p *GetCollectionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCollectionResult) GetResult() interface{} {
	return p.Success
}

func listCollectionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListCollectionsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).ListCollections(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListCollectionsArgs:
		success, err := handler.(v1.CatalogAdminService).ListCollections(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListCollectionsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListCollectionsArgs() interface{} {
	return &ListCollectionsArgs{}
}

func newListCollectionsResult() interface{} {
	return &ListCollectionsResult{}
}

type ListCollectionsArgs struct {
	Req *v1.ListCollectionsRequest
}

func (p *ListCollectionsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListCollectionsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListCollectionsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListCollectionsArgs_Req_DEFAULT *v1.ListCollectionsRequest

func (p *ListCollectionsArgs) GetReq() *v1.ListCollectionsRequest {
	if !p.IsSetReq() {
		return ListCollectionsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListCollectionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListCollectionsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListCollectionsResult struct {
	Success *v1.ListCollectionsResponse
}

var ListCollectionsResult_Success_DEFAULT *v1.ListCollectionsResponse

func (p *ListCollectionsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListCollectionsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListCollectionsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListCollectionsResult) GetSuccess() *v1.ListCollectionsResponse {
	if !p.IsSetSuccess() {
		return ListCollectionsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListCollectionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListCollectionsResponse)
}

func (p *ListCollectionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListCollectionsResult) GetResult() interface{} {
	return p.Success
}

func createSubscriptionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateSubscriptionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).CreateSubscription(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateSubscriptionArgs:
		success, err := handler.(v1.CatalogAdminService).CreateSubscription(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateSubscriptionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateSubscriptionArgs() interface{} {
	return &CreateSubscriptionArgs{}
}

func newCreateSubscriptionResult() interface{} {
	return &CreateSubscriptionResult{}
}

type CreateSubscriptionArgs struct {
	Req *v1.CreateSubscriptionRequest
}

func (p *CreateSubscriptionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateSubscriptionArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateSubscriptionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateSubscriptionArgs_Req_DEFAULT *v1.CreateSubscriptionRequest

func (p *CreateSubscriptionArgs) GetReq() *v1.CreateSubscriptionRequest {
	if !p.IsSetReq() {
		return CreateSubscriptionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateSubscriptionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateSubscriptionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateSubscriptionResult struct {
	Success *v1.CreateSubscriptionResponse
}

var CreateSubscriptionResult_Success_DEFAULT *v1.CreateSubscriptionResponse

func (p *CreateSubscriptionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateSubscriptionResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateSubscriptionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateSubscriptionResult) GetSuccess() *v1.CreateSubscriptionResponse {
	if !p.IsSetSuccess() {
		return CreateSubscriptionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateSubscriptionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateSubscriptionResponse)
}

func (p *CreateSubscriptionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateSubscriptionResult) GetResult() interface{} {
	return p.Success
}

func updateSubscriptionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdateSubscriptionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).UpdateSubscription(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateSubscriptionArgs:
		success, err := handler.(v1.CatalogAdminService).UpdateSubscription(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateSubscriptionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateSubscriptionArgs() interface{} {
	return &UpdateSubscriptionArgs{}
}

func newUpdateSubscriptionResult() interface{} {
	return &UpdateSubscriptionResult{}
}

type UpdateSubscriptionArgs struct {
	Req *v1.UpdateSubscriptionRequest
}

func (p *UpdateSubscriptionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateSubscriptionArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdateSubscriptionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateSubscriptionArgs_Req_DEFAULT *v1.UpdateSubscriptionRequest

func (p *UpdateSubscriptionArgs) GetReq() *v1.UpdateSubscriptionRequest {
	if !p.IsSetReq() {
		return UpdateSubscriptionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateSubscriptionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateSubscriptionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateSubscriptionResult struct {
	Success *v1.UpdateSubscriptionResponse
}

var UpdateSubscriptionResult_Success_DEFAULT *v1.UpdateSubscriptionResponse

func (p *UpdateSubscriptionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateSubscriptionResult) Unmarshal(in []byte) error {
	msg := new(v1.UpdateSubscriptionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateSubscriptionResult) GetSuccess() *v1.UpdateSubscriptionResponse {
	if !p.IsSetSuccess() {
		return UpdateSubscriptionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateSubscriptionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UpdateSubscriptionResponse)
}

func (p *UpdateSubscriptionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateSubscriptionResult) GetResult() interface{} {
	return p.Success
}

func listSubscriptionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListSubscriptionsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).ListSubscriptions(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListSubscriptionsArgs:
		success, err := handler.(v1.CatalogAdminService).ListSubscriptions(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListSubscriptionsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListSubscriptionsArgs() interface{} {
	return &ListSubscriptionsArgs{}
}

func newListSubscriptionsResult() interface{} {
	return &ListSubscriptionsResult{}
}

type ListSubscriptionsArgs struct {
	Req *v1.ListSubscriptionsRequest
}

func (p *ListSubscriptionsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListSubscriptionsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListSubscriptionsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListSubscriptionsArgs_Req_DEFAULT *v1.ListSubscriptionsRequest

func (p *ListSubscriptionsArgs) GetReq() *v1.ListSubscriptionsRequest {
	if !p.IsSetReq() {
		return ListSubscriptionsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListSubscriptionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListSubscriptionsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListSubscriptionsResult struct {
	Success *v1.ListSubscriptionsResponse
}

var ListSubscriptionsResult_Success_DEFAULT *v1.ListSubscriptionsResponse

func (p *ListSubscriptionsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListSubscriptionsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListSubscriptionsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListSubscriptionsResult) GetSuccess() *v1.ListSubscriptionsResponse {
	if !p.IsSetSuccess() {
		return ListSubscriptionsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListSubscriptionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListSubscriptionsResponse)
}

func (p *ListSubscriptionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListSubscriptionsResult) GetResult() interface{} {
	return p.Success
}

func createModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateModelRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).CreateModel(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateModelArgs:
		success, err := handler.(v1.CatalogAdminService).CreateModel(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateModelResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateModelArgs() interface{} {
	return &CreateModelArgs{}
}

func newCreateModelResult() interface{} {
	return &CreateModelResult{}
}

type CreateModelArgs struct {
	Req *v1.CreateModelRequest
}

func (p *CreateModelArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateModelArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateModelRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateModelArgs_Req_DEFAULT *v1.CreateModelRequest

func (p *CreateModelArgs) GetReq() *v1.CreateModelRequest {
	if !p.IsSetReq() {
		return CreateModelArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateModelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateModelArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateModelResult struct {
	Success *v1.CreateModelResponse
}

var CreateModelResult_Success_DEFAULT *v1.CreateModelResponse

func (p *CreateModelResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateModelResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateModelResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateModelResult) GetSuccess() *v1.CreateModelResponse {
	if !p.IsSetSuccess() {
		return CreateModelResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateModelResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateModelResponse)
}

func (p *CreateModelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateModelResult) GetResult() interface{} {
	return p.Success
}

func updateModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdateModelRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).UpdateModel(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateModelArgs:
		success, err := handler.(v1.CatalogAdminService).UpdateModel(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateModelResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateModelArgs() interface{} {
	return &UpdateModelArgs{}
}

func newUpdateModelResult() interface{} {
	return &UpdateModelResult{}
}

type UpdateModelArgs struct {
	Req *v1.UpdateModelRequest
}

func (p *UpdateModelArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateModelArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdateModelRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateModelArgs_Req_DEFAULT *v1.UpdateModelRequest

func (p *UpdateModelArgs) GetReq() *v1.UpdateModelRequest {
	if !p.IsSetReq() {
		return UpdateModelArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateModelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateModelArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateModelResult struct {
	Success *v1.UpdateModelResponse
}

var UpdateModelResult_Success_DEFAULT *v1.UpdateModelResponse

func (p *UpdateModelResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateModelResult) Unmarshal(in []byte) error {
	msg := new(v1.UpdateModelResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateModelResult) GetSuccess() *v1.UpdateModelResponse {
	if !p.IsSetSuccess() {
		return UpdateModelResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateModelResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UpdateModelResponse)
}

func (p *UpdateModelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateModelResult) GetResult() interface{} {
	return p.Success
}

func getModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetModelRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).GetModel(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetModelArgs:
		success, err := handler.(v1.CatalogAdminService).GetModel(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetModelResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetModelArgs() interface{} {
	return &GetModelArgs{}
}

func newGetModelResult() interface{} {
	return &GetModelResult{}
}

type GetModelArgs struct {
	Req *v1.GetModelRequest
}

func (p *GetModelArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetModelArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetModelRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetModelArgs_Req_DEFAULT *v1.GetModelRequest

func (p *GetModelArgs) GetReq() *v1.GetModelRequest {
	if !p.IsSetReq() {
		return GetModelArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetModelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetModelArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetModelResult struct {
	Success *v1.GetModelResponse
}

var GetModelResult_Success_DEFAULT *v1.GetModelResponse

func (p *GetModelResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetModelResult) Unmarshal(in []byte) error {
	msg := new(v1.GetModelResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetModelResult) GetSuccess() *v1.GetModelResponse {
	if !p.IsSetSuccess() {
		return GetModelResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetModelResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetModelResponse)
}

func (p *GetModelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetModelResult) GetResult() interface{} {
	return p.Success
}

func listModelsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListModelsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).ListModels(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListModelsArgs:
		success, err := handler.(v1.CatalogAdminService).ListModels(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListModelsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListModelsArgs() interface{} {
	return &ListModelsArgs{}
}

func newListModelsResult() interface{} {
	return &ListModelsResult{}
}

type ListModelsArgs struct {
	Req *v1.ListModelsRequest
}

func (p *ListModelsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListModelsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListModelsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListModelsArgs_Req_DEFAULT *v1.ListModelsRequest

func (p *ListModelsArgs) GetReq() *v1.ListModelsRequest {
	if !p.IsSetReq() {
		return ListModelsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListModelsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListModelsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListModelsResult struct {
	Success *v1.ListModelsResponse
}

var ListModelsResult_Success_DEFAULT *v1.ListModelsResponse

func (p *ListModelsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListModelsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListModelsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListModelsResult) GetSuccess() *v1.ListModelsResponse {
	if !p.IsSetSuccess() {
		return ListModelsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListModelsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListModelsResponse)
}

func (p *ListModelsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListModelsResult) GetResult() interface{} {
	return p.Success
}

func createReleaseTemplateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateReleaseTemplateRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).CreateReleaseTemplate(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateReleaseTemplateArgs:
		success, err := handler.(v1.CatalogAdminService).CreateReleaseTemplate(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateReleaseTemplateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateReleaseTemplateArgs() interface{} {
	return &CreateReleaseTemplateArgs{}
}

func newCreateReleaseTemplateResult() interface{} {
	return &CreateReleaseTemplateResult{}
}

type CreateReleaseTemplateArgs struct {
	Req *v1.CreateReleaseTemplateRequest
}

func (p *CreateReleaseTemplateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateReleaseTemplateArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateReleaseTemplateRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateReleaseTemplateArgs_Req_DEFAULT *v1.CreateReleaseTemplateRequest

func (p *CreateReleaseTemplateArgs) GetReq() *v1.CreateReleaseTemplateRequest {
	if !p.IsSetReq() {
		return CreateReleaseTemplateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateReleaseTemplateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateReleaseTemplateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateReleaseTemplateResult struct {
	Success *v1.CreateReleaseTemplateResponse
}

var CreateReleaseTemplateResult_Success_DEFAULT *v1.CreateReleaseTemplateResponse

func (p *CreateReleaseTemplateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateReleaseTemplateResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateReleaseTemplateResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateReleaseTemplateResult) GetSuccess() *v1.CreateReleaseTemplateResponse {
	if !p.IsSetSuccess() {
		return CreateReleaseTemplateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateReleaseTemplateResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateReleaseTemplateResponse)
}

func (p *CreateReleaseTemplateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateReleaseTemplateResult) GetResult() interface{} {
	return p.Success
}

func getReleaseTemplateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetReleaseTemplateRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).GetReleaseTemplate(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetReleaseTemplateArgs:
		success, err := handler.(v1.CatalogAdminService).GetReleaseTemplate(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetReleaseTemplateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetReleaseTemplateArgs() interface{} {
	return &GetReleaseTemplateArgs{}
}

func newGetReleaseTemplateResult() interface{} {
	return &GetReleaseTemplateResult{}
}

type GetReleaseTemplateArgs struct {
	Req *v1.GetReleaseTemplateRequest
}

func (p *GetReleaseTemplateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetReleaseTemplateArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetReleaseTemplateRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetReleaseTemplateArgs_Req_DEFAULT *v1.GetReleaseTemplateRequest

func (p *GetReleaseTemplateArgs) GetReq() *v1.GetReleaseTemplateRequest {
	if !p.IsSetReq() {
		return GetReleaseTemplateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetReleaseTemplateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetReleaseTemplateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetReleaseTemplateResult struct {
	Success *v1.GetReleaseTemplateResponse
}

var GetReleaseTemplateResult_Success_DEFAULT *v1.GetReleaseTemplateResponse

func (p *GetReleaseTemplateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetReleaseTemplateResult) Unmarshal(in []byte) error {
	msg := new(v1.GetReleaseTemplateResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetReleaseTemplateResult) GetSuccess() *v1.GetReleaseTemplateResponse {
	if !p.IsSetSuccess() {
		return GetReleaseTemplateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetReleaseTemplateResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetReleaseTemplateResponse)
}

func (p *GetReleaseTemplateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetReleaseTemplateResult) GetResult() interface{} {
	return p.Success
}

func listReleaseTemplatesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListReleaseTemplatesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.CatalogAdminService).ListReleaseTemplates(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListReleaseTemplatesArgs:
		success, err := handler.(v1.CatalogAdminService).ListReleaseTemplates(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListReleaseTemplatesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListReleaseTemplatesArgs() interface{} {
	return &ListReleaseTemplatesArgs{}
}

func newListReleaseTemplatesResult() interface{} {
	return &ListReleaseTemplatesResult{}
}

type ListReleaseTemplatesArgs struct {
	Req *v1.ListReleaseTemplatesRequest
}

func (p *ListReleaseTemplatesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListReleaseTemplatesArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListReleaseTemplatesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListReleaseTemplatesArgs_Req_DEFAULT *v1.ListReleaseTemplatesRequest

func (p *ListReleaseTemplatesArgs) GetReq() *v1.ListReleaseTemplatesRequest {
	if !p.IsSetReq() {
		return ListReleaseTemplatesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListReleaseTemplatesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListReleaseTemplatesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListReleaseTemplatesResult struct {
	Success *v1.ListReleaseTemplatesResponse
}

var ListReleaseTemplatesResult_Success_DEFAULT *v1.ListReleaseTemplatesResponse

func (p *ListReleaseTemplatesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListReleaseTemplatesResult) Unmarshal(in []byte) error {
	msg := new(v1.ListReleaseTemplatesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListReleaseTemplatesResult) GetSuccess() *v1.ListReleaseTemplatesResponse {
	if !p.IsSetSuccess() {
		return ListReleaseTemplatesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListReleaseTemplatesResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListReleaseTemplatesResponse)
}

func (p *ListReleaseTemplatesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListReleaseTemplatesResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateCollection(ctx context.Context, Req *v1.CreateCollectionRequest) (r *v1.CreateCollectionResponse, err error) {
	var _args CreateCollectionArgs
	_args.Req = Req
	var _result CreateCollectionResult
	if err = p.c.Call(ctx, "CreateCollection", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateCollection(ctx context.Context, Req *v1.UpdateCollectionRequest) (r *v1.UpdateCollectionResponse, err error) {
	var _args UpdateCollectionArgs
	_args.Req = Req
	var _result UpdateCollectionResult
	if err = p.c.Call(ctx, "UpdateCollection", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCollection(ctx context.Context, Req *v1.GetCollectionRequest) (r *v1.GetCollectionResponse, err error) {
	var _args GetCollectionArgs
	_args.Req = Req
	var _result GetCollectionResult
	if err = p.c.Call(ctx, "GetCollection", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListCollections(ctx context.Context, Req *v1.ListCollectionsRequest) (r *v1.ListCollectionsResponse, err error) {
	var _args ListCollectionsArgs
	_args.Req = Req
	var _result ListCollectionsResult
	if err = p.c.Call(ctx, "ListCollections", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateSubscription(ctx context.Context, Req *v1.CreateSubscriptionRequest) (r *v1.CreateSubscriptionResponse, err error) {
	var _args CreateSubscriptionArgs
	_args.Req = Req
	var _result CreateSubscriptionResult
	if err = p.c.Call(ctx, "CreateSubscription", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateSubscription(ctx context.Context, Req *v1.UpdateSubscriptionRequest) (r *v1.UpdateSubscriptionResponse, err error) {
	var _args UpdateSubscriptionArgs
	_args.Req = Req
	var _result UpdateSubscriptionResult
	if err = p.c.Call(ctx, "UpdateSubscription", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSubscriptions(ctx context.Context, Req *v1.ListSubscriptionsRequest) (r *v1.ListSubscriptionsResponse, err error) {
	var _args ListSubscriptionsArgs
	_args.Req = Req
	var _result ListSubscriptionsResult
	if err = p.c.Call(ctx, "ListSubscriptions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateModel(ctx context.Context, Req *v1.CreateModelRequest) (r *v1.CreateModelResponse, err error) {
	var _args CreateModelArgs
	_args.Req = Req
	var _result CreateModelResult
	if err = p.c.Call(ctx, "CreateModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateModel(ctx context.Context, Req *v1.UpdateModelRequest) (r *v1.UpdateModelResponse, err error) {
	var _args UpdateModelArgs
	_args.Req = Req
	var _result UpdateModelResult
	if err = p.c.Call(ctx, "UpdateModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetModel(ctx context.Context, Req *v1.GetModelRequest) (r *v1.GetModelResponse, err error) {
	var _args GetModelArgs
	_args.Req = Req
	var _result GetModelResult
	if err = p.c.Call(ctx, "GetModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListModels(ctx context.Context, Req *v1.ListModelsRequest) (r *v1.ListModelsResponse, err error) {
	var _args ListModelsArgs
	_args.Req = Req
	var _result ListModelsResult
	if err = p.c.Call(ctx, "ListModels", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateReleaseTemplate(ctx context.Context, Req *v1.CreateReleaseTemplateRequest) (r *v1.CreateReleaseTemplateResponse, err error) {
	var _args CreateReleaseTemplateArgs
	_args.Req = Req
	var _result CreateReleaseTemplateResult
	if err = p.c.Call(ctx, "CreateReleaseTemplate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetReleaseTemplate(ctx context.Context, Req *v1.GetReleaseTemplateRequest) (r *v1.GetReleaseTemplateResponse, err error) {
	var _args GetReleaseTemplateArgs
	_args.Req = Req
	var _result GetReleaseTemplateResult
	if err = p.c.Call(ctx, "GetReleaseTemplate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListReleaseTemplates(ctx context.Context, Req *v1.ListReleaseTemplatesRequest) (r *v1.ListReleaseTemplatesResponse, err error) {
	var _args ListReleaseTemplatesArgs
	_args.Req = Req
	var _result ListReleaseTemplatesResult
	if err = p.c.Call(ctx, "ListReleaseTemplates", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
