// Code generated by Kitex v0.16.2. DO NOT EDIT.

package configservice

import (
	"context"
	v1 "github.com/asherzj/financial_configuration_center/contracts/kitex_gen/finconfig/config/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streamclient "github.com/cloudwego/kitex/client/streamclient"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetSnapshot(ctx context.Context, Req *v1.GetSnapshotRequest, callOptions ...callopt.Option) (r *v1.GetSnapshotResponse, err error)
	DiffVersions(ctx context.Context, Req *v1.DiffVersionsRequest, callOptions ...callopt.Option) (r *v1.DiffVersionsResponse, err error)
	GetCollections(ctx context.Context, Req *v1.GetCollectionsRequest, callOptions ...callopt.Option) (r *v1.GetCollectionsResponse, err error)
	Watch(ctx context.Context, Req *v1.WatchRequest, callOptions ...callopt.Option) (stream ConfigService_WatchClient, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	Watch(ctx context.Context, Req *v1.WatchRequest, callOptions ...streamcall.Option) (stream ConfigService_WatchClient, err error)
}

type ConfigService_WatchClient interface {
	streaming.Stream
	Recv() (*v1.WatchResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kConfigServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConfigServiceClient struct {
	*kClient
}

func (p *kConfigServiceClient) GetSnapshot(ctx context.Context, Req *v1.GetSnapshotRequest, callOptions ...callopt.Option) (r *v1.GetSnapshotResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSnapshot(ctx, Req)
}

func (p *kConfigServiceClient) DiffVersions(ctx context.Context, Req *v1.DiffVersionsRequest, callOptions ...callopt.Option) (r *v1.DiffVersionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DiffVersions(ctx, Req)
}

func (p *kConfigServiceClient) GetCollections(ctx context.Context, Req *v1.GetCollectionsRequest, callOptions ...callopt.Option) (r *v1.GetCollectionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCollections(ctx, Req)
}

func (p *kConfigServiceClient) Watch(ctx context.Context, Req *v1.WatchRequest, callOptions ...callopt.Option) (stream ConfigService_WatchClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Watch(ctx, Req)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kConfigServiceStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConfigServiceStreamClient struct {
	*kClient
}

func (p *kConfigServiceStreamClient) Watch(ctx context.Context, Req *v1.WatchRequest, callOptions ...streamcall.Option) (stream ConfigService_WatchClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.Watch(ctx, Req)
}
