// Code generated by Kitex v0.16.2. DO NOT EDIT.

package configservice

import (
	"context"
	"errors"
	"fmt"
	v1 "github.com/asherzj/financial_configuration_center/contracts/kitex_gen/finconfig/config/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetSnapshot": kitex.NewMethodInfo(
		getSnapshotHandler,
		newGetSnapshotArgs,
		newGetSnapshotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DiffVersions": kitex.NewMethodInfo(
		diffVersionsHandler,
		newDiffVersionsArgs,
		newDiffVersionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetCollections": kitex.NewMethodInfo(
		getCollectionsHandler,
		newGetCollectionsArgs,
		newGetCollectionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Watch": kitex.NewMethodInfo(
		watchHandler,
		newWatchArgs,
		newWatchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
}

var (
	configServiceServiceInfo                = NewServiceInfo()
	configServiceServiceInfoForClient       = NewServiceInfoForClient()
	configServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return configServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return configServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return configServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ConfigService"
	handlerType := (*v1.ConfigService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finconfig.config.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func getSnapshotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetSnapshotRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.ConfigService).GetSnapshot(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetSnapshotArgs:
		success, err := handler.(v1.ConfigService).GetSnapshot(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetSnapshotResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetSnapshotArgs() interface{} {
	return &GetSnapshotArgs{}
}

func newGetSnapshotResult() interface{} {
	return &GetSnapshotResult{}
}

type GetSnapshotArgs struct {
	Req *v1.GetSnapshotRequest
}

func (p *GetSnapshotArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetSnapshotArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetSnapshotRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetSnapshotArgs_Req_DEFAULT *v1.GetSnapshotRequest

func (p *GetSnapshotArgs) GetReq() *v1.GetSnapshotRequest {
	if !p.IsSetReq() {
		return GetSnapshotArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetSnapshotArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetSnapshotArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetSnapshotResult struct {
	Success *v1.GetSnapshotResponse
}

var GetSnapshotResult_Success_DEFAULT *v1.GetSnapshotResponse

func (p *GetSnapshotResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetSnapshotResult) Unmarshal(in []byte) error {
	msg := new(v1.GetSnapshotResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetSnapshotResult) GetSuccess() *v1.GetSnapshotResponse {
	if !p.IsSetSuccess() {
		return GetSnapshotResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetSnapshotResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetSnapshotResponse)
}

func (p *GetSnapshotResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetSnapshotResult) GetResult() interface{} {
	return p.Success
}

func diffVersionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DiffVersionsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.ConfigService).DiffVersions(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DiffVersionsArgs:
		success, err := handler.(v1.ConfigService).DiffVersions(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DiffVersionsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDiffVersionsArgs() interface{} {
	return &DiffVersionsArgs{}
}

func newDiffVersionsResult() interface{} {
	return &DiffVersionsResult{}
}

type DiffVersionsArgs struct {
	Req *v1.DiffVersionsRequest
}

func (p *DiffVersionsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DiffVersionsArgs) Unmarshal(in []byte) error {
	msg := new(v1.DiffVersionsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DiffVersionsArgs_Req_DEFAULT *v1.DiffVersionsRequest

func (p *DiffVersionsArgs) GetReq() *v1.DiffVersionsRequest {
	if !p.IsSetReq() {
		return DiffVersionsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DiffVersionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DiffVersionsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DiffVersionsResult struct {
	Success *v1.DiffVersionsResponse
}

var DiffVersionsResult_Success_DEFAULT *v1.DiffVersionsResponse

func (p *DiffVersionsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DiffVersionsResult) Unmarshal(in []byte) error {
	msg := new(v1.DiffVersionsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DiffVersionsResult) GetSuccess() *v1.DiffVersionsResponse {
	if !p.IsSetSuccess() {
		return DiffVersionsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DiffVersionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.DiffVersionsResponse)
}

func (p *DiffVersionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DiffVersionsResult) GetResult() interface{} {
	return p.Success
}

func getCollectionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetCollectionsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.ConfigService).GetCollections(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetCollectionsArgs:
		success, err := handler.(v1.ConfigService).GetCollections(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCollectionsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetCollectionsArgs() interface{} {
	return &GetCollectionsArgs{}
}

func newGetCollectionsResult() interface{} {
	return &GetCollectionsResult{}
}

type GetCollectionsArgs struct {
	Req *v1.GetCollectionsRequest
}

func (p *GetCollectionsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetCollectionsArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetCollectionsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCollectionsArgs_Req_DEFAULT *v1.GetCollectionsRequest

func (p *GetCollectionsArgs) GetReq() *v1.GetCollectionsRequest {
	if !p.IsSetReq() {
		return GetCollectionsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCollectionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCollectionsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCollectionsResult struct {
	Success *v1.GetCollectionsResponse
}

var GetCollectionsResult_Success_DEFAULT *v1.GetCollectionsResponse

func (p *GetCollectionsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetCollectionsResult) Unmarshal(in []byte) error {
	msg := new(v1.GetCollectionsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCollectionsResult) GetSuccess() *v1.GetCollectionsResponse {
	if !p.IsSetSuccess() {
		return GetCollectionsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCollectionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetCollectionsResponse)
}

func (p *GetCollectionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCollectionsResult) GetResult() interface{} {
	return p.Success
}

func watchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &configServiceWatchServer{st}
	req := new(v1.WatchRequest)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(v1.ConfigService).Watch(req, stream)
}

type configServiceWatchClient struct {
	streaming.Stream
}

func (x *configServiceWatchClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *configServiceWatchClient) Recv() (*v1.WatchResponse, error) {
	m := new(v1.WatchResponse)
	return m, x.Stream.RecvMsg(m)
}

type configServiceWatchServer struct {
	streaming.Stream
}

func (x *configServiceWatchServer) Send(m *v1.WatchResponse) error {
	return x.Stream.SendMsg(m)
}

func newWatchArgs() interface{} {
	return &WatchArgs{}
}

func newWatchResult() interface{} {
	return &WatchResult{}
}

type WatchArgs struct {
	Req *v1.WatchRequest
}

func (p *WatchArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *WatchArgs) Unmarshal(in []byte) error {
	msg := new(v1.WatchRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var WatchArgs_Req_DEFAULT *v1.WatchRequest

func (p *WatchArgs) GetReq() *v1.WatchRequest {
	if !p.IsSetReq() {
		return WatchArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *WatchArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *WatchArgs) GetFirstArgument() interface{} {
	return p.Req
}

type WatchResult struct {
	Success *v1.WatchResponse
}

var WatchResult_Success_DEFAULT *v1.WatchResponse

func (p *WatchResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *WatchResult) Unmarshal(in []byte) error {
	msg := new(v1.WatchResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *WatchResult) GetSuccess() *v1.WatchResponse {
	if !p.IsSetSuccess() {
		return WatchResult_Success_DEFAULT
	}
	return p.Success
}

func (p *WatchResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.WatchResponse)
}

func (p *WatchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *WatchResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetSnapshot(ctx context.Context, Req *v1.GetSnapshotRequest) (r *v1.GetSnapshotResponse, err error) {
	var _args GetSnapshotArgs
	_args.Req = Req
	var _result GetSnapshotResult
	if err = p.c.Call(ctx, "GetSnapshot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DiffVersions(ctx context.Context, Req *v1.DiffVersionsRequest) (r *v1.DiffVersionsResponse, err error) {
	var _args DiffVersionsArgs
	_args.Req = Req
	var _result DiffVersionsResult
	if err = p.c.Call(ctx, "DiffVersions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCollections(ctx context.Context, Req *v1.GetCollectionsRequest) (r *v1.GetCollectionsResponse, err error) {
	var _args GetCollectionsArgs
	_args.Req = Req
	var _result GetCollectionsResult
	if err = p.c.Call(ctx, "GetCollections", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Watch(ctx context.Context, req *v1.WatchRequest) (ConfigService_WatchClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "Watch", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &configServiceWatchClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}
